# Generated by Django 4.0.5 on 2022-06-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_directory_remove_movie_director_delete_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie_app.directory'),
        ),
    ]
