# Generated by Django 4.0.5 on 2022-06-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_alter_movie_directory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directory',
            new_name='Director',
        ),
    ]
